version: '3.4'

services:
  api:
    build:
      context: ./go-api
    container_name: challe-chara2022-api
    stdin_open: true
    tty: true
    ports:
      - "8080:8080"
    environment:
      MONGO_URI: ${MONGO_URI}
      GO111MODULE: "on"
      PORT: "8080"
    volumes:
      - ./go-api:/api

  
  mongo:
    image: mongo:latest
    restart: always
    environment:
        MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
        MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - 27017:27017
    container_name: mongo
    hostname: mongo
    tty: true
    stdin_open: true
    volumes:
      # 初期データを投入するシェルスクリプトが格納されているdir
      - ./db/mongo_init:/docker-entrypoint-initdb.d
      # データの永続化
      - ./db_data:/data/db
      - ./configdb:/data/configdb

  # Local S3のコンテナ
  minio:
    image: minio/minio:RELEASE.2021-06-17T00-10-46Z
    container_name: minio_qmatta
    environment:
        MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
        MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    entrypoint: bash

    # バケット設定情報格納フォルダの作成
    # バケットポリシーをコピー
    # 初期データをコピー（bucket自体は /data に作成される）
    # s3サーバ起動
    command: -c "
      mkdir -p /data/.minio.sys/buckets;
      cp -r /policies/* /data/.minio.sys/;
      cp -r /export/* /data/;
      /usr/bin/minio server /data;"

    volumes:
        - ./minio/data:/data # データの永続化
        - ./minio/export:/export
        - ./minio/config:/root/.minio 
        - ./minio/policies:/policies

    ports:
       - 9090:9000


# volumeを定義
volumes:
  db_data: