version: '3.4'

services:
  api:
    build:
      context: ./go-api
    container_name: challe-chara2022-api
    stdin_open: true
    tty: true
    environment:
      CLUSTER_NAME: qmatta
      COUCHBASE_ADMINISTRATOR_USERNAME: couchbase
      COUCHBASE_ADMINISTRATOR_PASSWORD: lcouchbase1
      COUCHBASE_BUCKET: default
      COUCHBASE_HOST: couch_db
      COUCHBSE_SCHEME: couchbases://
      GO111MODULE: "on"
      PORT: "8080"
    volumes:
      - ./go-api:/api

  couch_db:
    build: ./mbe-couchbase-container
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 8094:8094
      - 11210:11210
      - 11211:11211
    environment:
      CLUSTER_NAME: qmatta
      COUCHBASE_ADMINISTRATOR_USERNAME: couchbase
      COUCHBASE_ADMINISTRATOR_PASSWORD: lcouchbase1
      COUCHBASE_BUCKET: default
      COUCHBASE_HOST: couch_db
      COUCHBSE_SCHEME: couchbase://
    container_name: couch_db
    hostname: couch_db
    tty: true
    stdin_open: true
    volumes:
      # データの永続化
      - ./db/db_data:/var/lib/couchbase/data

  sync-gateway:
    image: couchbase/sync-gateway:1.4.0-2
    ports:
      - "4984"
    volumes:
      - ./sync-gateway-config.json:/etc/sync_gateway/config.json

# volumeを定義
volumes:
  db_data: