version: '3.4'

services:
  api:
    build:
      context: ./go-api
    container_name: challe-chara2022-api
    stdin_open: true
    tty: true
    environment:
      MONGO_URI: mongodb://root:root@mongo:27017/?maxIdleTimeMS=30&maxPoolSize=20
      GO111MODULE: "on"
      PORT: "8080"
    volumes:
      - ./go-api:/api

  
  mongo:
    image: mongo:latest
    restart: always
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    container_name: mongo
    hostname: mongo
    tty: true
    stdin_open: true
    volumes:
      # 初期データを投入するシェルスクリプトが格納されているdir
      - ./db/mongo_init:/docker-entrypoint-initdb.d
      # データの永続化
      - ./db_data:/data/db
      - ./configdb:/data/configdb

# volumeを定義
volumes:
  db_data: