version: 2.1
jobs:
  build:
    working_directory: ~/repo 
    docker:
      - image: cimg/go:1.18
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go-api/go.sum" }}
      - run:
          name: Install Dependencies
          command: cd go-api && go mod tidy 
      - save_cache:
          key: go-mod-v4-{{ checksum "go-api/go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Run tests
          command: go test -v